## The np.einsum() function

Before we get into the modelling, we introduce numpy's 'einsum' function since we'll often be relying on it's practicality and elegance in the ensuing sections. The 'einsum' function takes three mandatory arguments. Firstly, it takes (at least) two numpy arrays, say $a$ and $b$. These may be of any dimension. Secondly, it takes a string of 'subscripts' which corresponds to axes the of $a$, $b$, an 'explicit indicator' i.e. the symbol'->', and the axes of the output. E.g. if $a$ and $b$ are $2\times 3$- and $3\times 1$ matrices, respectively, then the subscript 'nj,jk->nk' corresponds to computing the matrix product $ab$. 'einsum' is also capable of computing various other linear algebraic operations such as transposes, outer products, elementwise products, etc.

In the following, we include some examples of 'einsum'-functions functionality with the hope of claryfying our model implementation.

In [1]:
import numpy as np
import pandas as pd 

Firstly, we define some numpy.array objects on which to operate.

In [2]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[[1,2], [3,4], [5,6]], [[11,12], [13,14] ,[15,16]]])
C = np.array([1,2])

pd.DataFrame({name : [X.shape] for name, X in zip(['A', 'B', 'C'], [A, B, C])}) # dimensions and axes lengths of arrays

A          B     C
0  (2, 3)  (2, 3, 2)  (2,)

As mentioned we may we compute ordinary matrix products using einsum in the following way

In [3]:
np.einsum('njk,ki->nji', B, A) # Is equivalent to B @ A

array([[[  9,  12,  15],
        [ 19,  26,  33],
        [ 29,  40,  51]],

       [[ 59,  82, 105],
        [ 69,  96, 123],
        [ 79, 110, 141]]])

'einsum' is also capable of transposing matrices 'on the fly' when doing operations. Consider for example the following modifcation of the above matrix product

In [4]:
np.einsum('ki,njk->nji', A, B) # Is equivalent to np.transpose(A) @ np.transpose(B)

array([[[  9,  12,  15],
        [ 19,  26,  33],
        [ 29,  40,  51]],

       [[ 59,  82, 105],
        [ 69,  96, 123],
        [ 79, 110, 141]]])

We can also easily calculate outer products

In [5]:
np.einsum('j,i->ji', C, C)

array([[1, 2],
       [2, 4]])

And this also possible for multi dimensional matrices...

In [6]:
np.einsum('njk,i->njki', B, C)

array([[[[ 1,  2],
         [ 2,  4]],

        [[ 3,  6],
         [ 4,  8]],

        [[ 5, 10],
         [ 6, 12]]],


       [[[11, 22],
         [12, 24]],

        [[13, 26],
         [14, 28]],

        [[15, 30],
         [16, 32]]]])

Furthermore, we may compute elementwise products

In [7]:
np.einsum('nj,nj->nj', A, A)

array([[ 1,  4,  9],
       [16, 25, 36]])

Which may also be done on multidimensional matrices of different dimensions

In [8]:
np.einsum('njk,nj->njk', B, A) # This computation can also be achieved by B*A[:,:,None]. Note that 'einsum' permutes/transposes/matches the dimensions of B and A before computing the product. 

array([[[ 1,  2],
        [ 6,  8],
        [15, 18]],

       [[44, 48],
        [65, 70],
        [90, 96]]])

Lastly, 'einsum' can also do operations involving more than two numpy array. For example, the following code outputs a matrix product

In [11]:
np.einsum('nj,njk,ki->ni', A, B, A)  

array([[ 134,  184,  234],
       [1055, 1468, 1881]])